version: "3.7"

networks:
  local:
    name: local
    driver: bridge
    ipam:
      config:
        - subnet: 172.86.1.0/24

volumes:
  bitcoin:
  lnd:

services:
  bitcoin:
    image: vafanassieff/bitcoin:0.21.0
    container_name: bitcoin
    hostname: bitcoin
    restart: unless-stopped
    volumes:
      - bitcoin:/bitcoin/.bitcoin
      - ./config/bitcoin.conf:/conf/bitcoin.conf:rw
    networks:
      - local
    command: bitcoind -conf=/conf/bitcoin.conf

  lnd:
    image: vafanassieff/lnd:v0.12.1-beta
    container_name: lnd
    hostname: lnd
    restart: unless-stopped
    environment:
      - BITCOIND_RPCPASS=test
    volumes:
      - lnd:/lnd/.lnd
      - ./config/lnd.conf:/conf/lnd.conf:rw
    networks:
      - local
    depends_on:
      - bitcoin
    command: lnd --configfile=/conf/lnd.conf
