name: lndmon

on:
  push:
    branches:
      - "master"
    paths:
      - "lndmon/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: |
          echo 'VERSION='$(grep 'ENV LNDMON_VERSION=' lndmon/Dockerfile | cut -f2- -d=) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        run: grep 'ENV LNDMON_VERSION=' lndmon/Dockerfile | cut -f2- -d=
        env:
          TAG1: "devmtl/rclone:2.29.1-2019-08-24-32c812f7"
          TAG2: "devmtl/rclone:2.29.edge"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: lndmon
          push: true
          tags: |
            ghcr.io/vafanassieff/lndmon:latest
            ghcr.io/vafanassieff/lndmon:${{ env.VERSION }}
            vafanassieff/lndmon:latest
            vafanassieff/lndmon:${{ env.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
